version: '3.8'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3001:3001' # different port probably change later

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app    # Dot at the begining make it a mounted volume
      - /app/node_modules # Named volume = no dot
    ports:
      - '3000:3000'

  postgres:
    image: postgres:11-alpine
    restart: unless-stopped
    volumes:
      - ./database-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}