version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3001:3001' # different port probably change later
  
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:alpine3.18
    restart: unless-stopped
    volumes:
      - ./database-data:/var/lib/postgresql/data
      # - ./postgres/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  nginx:
    container_name: nginx
    image: nginx:mainline-alpine3.18-slim
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf